logging:
  level.root: WARN
  level.no.fdk: ${LOG_LEVEL:INFO}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080

---
spring:
  config.activate.on-profile: test



