apiVersion: v1
kind: Service
metadata:
  labels:
    app: access-request-api
  name: access-request-api
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: access-request-api
