apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: access-request-api
  name: access-request-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: access-request-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: access-request-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"  
    spec:
      containers:
        - name: access-request-api
          image: access-request-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
              cpu: "100m"
            limits:
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
