---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - access-request-api-deployment.yaml
  - access-request-api-service.yaml
images:
  - name: access-request-api
    newName: eu.gcr.io/digdir-fdk-infra/access-request-api
    newTag: $(GIT_COMMIT_SHA)
